### ISSUE TITLE
run.sh fails

### ISSUE THREAD

**Issue by jimstarace** [sherzberg/wercker-step-slack-notify#11]
on after build steps when wercker-slack-notify step executes there is an error

cd $WERCKER_SOURCE_DIR
$ export WERCKER_STEP_ROOT="/wercker/steps/sherzberg/slack-notify/0.0.6"
$ export WERCKER_STEP_ID="87269683-0b52-4a0c-97c3-07c728a4bf80"
$ export WERCKER_STEP_NAME="slack-notify"
$ export WERCKER_REPORT_NUMBERS_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/numbers.ini"
$ export WERCKER_REPORT_MESSAGE_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/message.txt"
$ export WERCKER_REPORT_ARTIFACTS_DIR="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/artifacts"
$ mkdir -p $WERCKER_REPORT_ARTIFACTS_DIR
$ export WERCKER_STEP_TEMP="/tmp/$WERCKER_STEP_ID"
$ source '/wercker/wercker-build-essentials/init.sh'
$ mkdir -p $WERCKER_STEP_TEMP
$ export WERCKER_SLACK_NOTIFY_SUBDOMAIN="agencyaccess"
$ export WERCKER_SLACK_NOTIFY_TOKEN="$SLACK_TOKEN"
$ export WERCKER_SLACK_NOTIFY_CHANNEL="axs_info"
$ source "$WERCKER_STEP_ROOT/run.sh"
-bash: fatal: command not found

**Comment by wiiiimm** [comment]
@jimstarace your $SLACK_TOKEN is missing?

**Comment by jimstarace** [comment]
My $SLACK_TOKEN is defined as a variable in the build pipeline on wercker. Even when I put the token into the wercker.yml directly I get the same result. I have even tried the step you committed to the wercker directory (williamli/slack-notify-no-owner-info) and same result. All other steps in my wercker.yml work just fine, even those with variables defined in the pipeline.

Am I reading the log correctly that run.sh does not exist in the $WERCKER_STEP_ROOT/ directory?

**Comment by wiiiimm** [comment]
@jimstarace which version of williamli/slack-notify-no-owner-info were you using? I had some problems with my code in version before 0.0.8 that caused '-bash: fatal: command not found’ for other reasons…

my after steps are defined as

after-steps:
    - williamli/slack-notify-no-owner-info:
        subdomain: pixls
        token: ###########my token########
        channel: codebuzz

**Comment by jimstarace** [comment]
mine that fail are the same which when validating the file shows version 0.0.8

```
- williamli/slack-notify-no-owner-info:
    subdomain: agencyaccess
    token: xxxxxxxxxxxxMY-Token-xxxxxxxxxxxxx
    channel: axs_info
```

**Comment by wiiiimm** [comment]
@jimstarace would you like file this under my repo? it is working fine for me now so i am almost sure there is something wrong in your settings.

**Comment by aaroneaton** [comment]
I'd just like to add that I'm getting the same issue. I've tried with using env. variables and hardcoded.

``` yml
  after-steps:
    - sherzberg/slack-notify:
        subdomain: $SLACK_SUBDOMAIN
        token: $SLACK_TOKEN
        channel: $SLACK_CHANNEL
```

Getting the following in Wercker:

```
cd $WERCKER_SOURCE_DIR
$ export WERCKER_STEP_ROOT="/wercker/steps/sherzberg/slack-notify/0.0.6"
$ export WERCKER_STEP_ID="02afeb17-bab0-4adf-b51b-a39602f2f592"
$ export WERCKER_STEP_NAME="slack-notify"
$ export WERCKER_REPORT_NUMBERS_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/numbers.ini"
$ export WERCKER_REPORT_MESSAGE_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/message.txt"
$ export WERCKER_REPORT_ARTIFACTS_DIR="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/artifacts"
$ mkdir -p $WERCKER_REPORT_ARTIFACTS_DIR
$ export WERCKER_STEP_TEMP="/tmp/$WERCKER_STEP_ID"
$ source '/wercker/wercker-build-essentials/init.sh'
$ mkdir -p $WERCKER_STEP_TEMP
$ export WERCKER_SLACK_NOTIFY_SUBDOMAIN="$SLACK_SUBDOMAIN"
$ export WERCKER_SLACK_NOTIFY_TOKEN="$SLACK_TOKEN"
$ export WERCKER_SLACK_NOTIFY_CHANNEL="$SLACK_CHANNEL"
$ source "$WERCKER_STEP_ROOT/run.sh"
-bash: fatal: command not found
```

**Comment by sherzberg** [comment]
@channeleaton are you sure the environment variable is set in the settings of the wercker build? Do you have SLACK_TOKEN or $SLACK_TOKEN set there? SLACK_TOKEN without the $ should be in the environment variable settings. Sorry for the late response.

**Comment by mastef** [comment]
this is because 'fatal' is not included with wercker. so if an error is raised, fatal is called, which does not exist

```
<@hatchan> wercker provides a few bash functions, but fatal isnt one of them :(
<@hatchan> theses are supported: success info debug warn error fail
```

**Comment by mastef** [comment]
this might be the solution for now

```
  after-steps:
    - script:
        name: define fatal
        code: |
          function fatal() { print "$@" ; exit 1 ; }
    - sherzberg/slack-notify:
        subdomain: $SLACK_SUBDOMAIN
        token: $SLACK_TOKEN
        channel: $SLACK_CHANNEL
```

**Comment by sherzberg** [comment]
Will changing fatal to fail be sufficient?

**Comment by hatchan** [comment]
Replacing `fatal` with `fail` should solve the `-bash: fatal: command not found` error.

This is the implementation of `fail`:

``` bash
function fail() {
    _message "failed: ${1}" $ERROR_COLOR
    echo "${1}" > "$WERCKER_REPORT_MESSAGE_FILE"
    exit 1
}
```

So the best usage is to use a short error message (max 1 line), if you need any more logging then you best use `error` before `fail`.

**Comment by caifara** [comment]
Since some days, we're seeing the exact same issue on all of our projects without any change to the wercker.yml file nor ENV variables. Any ideas?

**Comment by sherzberg** [comment]
@caifara do you have your SLACK_TOKEN set in the environment variables in the wercker admin?

**Comment by caifara** [comment]
It is set correctly (as pipeline vars). I investigated the logs a bit further, it worked with 0.0.8, it's 0.0.11 that doesn't work which seems to be in use since 8 days according to the logs. 

our wercker file contains after steps in the build and deploy fase, both don't work:

```
    after-steps:
        - sherzberg/slack-notify:
            subdomain: by2
            token: $SLACK_TOKEN
            channel: general
            username: wercker
            avatar_url: https://avatars3.githubusercontent.com/u/1695193?s=140
```
